### ISSUE TITLE
get data in controller

### ISSUE THREAD

**Issue by omidmm16** [mabuonomo/nestjs-guard-grpc#1]
Hi Mr. Buanomo.
first thanks for publishing this method. 
I couldn't get data  and user at the same time. but I need both . 
```
 @GrpcMethod('UserService', 'FindAll')
  findAll(@GRPCUser() user: User, data:any ,metadata: any) {
    console.log('User injected', user);
    return [];
  }
```

**Comment by mabuonomo** [comment]
hi @omidmm16 you must change the signature of your method, in your proto file, to allow the new extra field

**Comment by omidmm16** [comment]
if I don't need user object, I can get data . but at the same time , I just can use one of them. 

 
rpc SetPassword (SetPasswordInput) returns (SetPasswordRes){}


`
  @GrpcMethod('UserClient', 'SetPassword')

  async setPassword(@GRPCUser user,data:SetPasswordInput, metadata: any): Promise<SetPasswordRes> {
    console.log('User injected', user);
    return {
      username: '',
      userId: '',
      message: `password ${metadata.password} - ${metadata.repeatPassword}`,
      statusCode: 200,
    };
`
what should I do? 

thanks

**Comment by mabuonomo** [comment]
you must change your interface (and proto), for example
```ts
interface UserClient {
setPassword(user: any, data: data:SetPasswordInput, metadata: grpc.Metadata): Promise;
}
```

**Comment by omidmm16** [comment]
in proto file signature,  we should add only data message,  We can't add user decorator in that,

https://github.com/nestjs/docs.nestjs.com/issues/715, 
https://github.com/nestjs/nest/issues/2596
Nest contributor solves this problem, but I can't do it.

in your mind, what shall we do?

thanks

**Comment by mabuonomo** [comment]
https://github.com/nestjs/nest/issues/4851 this link can help you?
Maybe you may use also a Payload decorator

**Comment by omidmm16** [comment]
I didn't see this Issue. 
with payload, I can get data, and decorator .
thank you so much. 
 @mabuonomo.👍 👍 👍
